services:
  user-api:
    container_name: user-api
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    image: user-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - arandu-network

networks:
  arandu-network:
    driver: bridge